### ISSUE TITLE
Get stylish-haskell to stop choking on Language.CapNProto.TH

### ISSUE THREAD

**Issue by zenhack** [zenhack/haskell-capnp#20]
Right now when I run the tool I get this:

```
Language.Haskell.Stylish.Parse.parseModule: could not parse library/Language/CapNProto/TH.hs: ParseFailed (SrcLoc "<unknown>.hs" 61 46) "Parse error in pattern: $( conP parentConName [varP struct] )"
```

It works fine with GHC, so presumably another descrepency between the parsers. Shouldn't be too hard to work around.

**Comment by taktoa** [comment]
Take a look at https://github.com/haskell-suite/haskell-src-exts/issues/338

**Comment by zenhack** [comment]
Looks like the upstream fix for this has finally been merged; closing.
