### ISSUE TITLE
Add .stylish-haskell.yaml

### ISSUE THREAD

**Issue by taktoa** [zenhack/haskell-capnp#4]
If someone who uses [stylish-haskell](https://github.com/jaspervdj/stylish-haskell) wants to contribute to this repository, they have to add a gitignored `.stylish-haskell.yaml` containing only `steps: {}`, or else their diff will be much larger than is probably reasonable. Thus, I am of the opinion that _every_ Haskell project that intends to have outside contributions should contain a `.stylish-haskell.yaml`, even if only to opt out of the formatting. If you are interested in having the formatting, then you can of course choose whatever configuration you desire, but you should make a choice. Personally, I use [this](https://github.com/awakesecurity/language-ninja/blob/master/.stylish-haskell.yaml) configuration.

**Comment by zenhack** [comment]
Works for me, done. Per the commit message I might mess around with actually having it do something later, but I just pushed a noop config for now.
