### ISSUE TITLE
missing .Pure import for class instances

### ISSUE THREAD

**Issue by p4l1ly** [zenhack/haskell-capnp#72]
Using the current `master` branch, the build of the generated files fails because of the [this](https://gist.github.com/p4l1ly/de7f9f4f4c80ceedae1bf50f29d06238#file-pure-hs-L26) missing import. No function from the import is used directly but its instance declarations are needed. . The minimal setup is expressed in the linked gist. To reproduce, just issue `cabal build`.

I feel that the fix would be trivial (just always import `.Pure` versions in `.Pure` modules in addition to the impure ones) but ~~I'm afraid I'm still not familiar enough with the generator code to be able to help you with a pull request~~. EDIT: I could not resist :slightly_smiling_face:

**Comment by zenhack** [comment]
Good catch. I'll try to find time to look at the PR later today or tomorrow.
