### ISSUE TITLE
BigEndian

### ISSUE THREAD

**Issue by lehins** [zenhack/haskell-capnp#84]
I'd like to point out that there is a bug in ghc <8 .10 that makes this code to not work correctly on Big Endian machines: https://gitlab.haskell.org/ghc/ghc/-/issues/20338

https://github.com/zenhack/haskell-capnp/blob/52cf97c2b99b031e72a0a86cf56407fc6621fb5f/lib/Capnp/Message.hs#L111-L116

**Comment by zenhack** [comment]
Thanks for letting me know. I'm waffling a bit on the right way to address this, but am leaning towards putting out a metadata revision bumping the lower bound on the compiler version, so nobody tries to build this with older compilers and finds this out the hard way. It's a bit sad in that it will block such builds even on machines where this works fine, but I don't actually want to invest effort in supporting older compilers, so maybe that's the best I can do.

**Comment by lehins** [comment]
Sure. I wasted a bunch of time elsewhere on this problem. So, i'd like to potentially save some time for others.
