### ISSUE TITLE
Missing documentation for capnp-0.15.0.0 on Hackage

### ISSUE THREAD

**Issue by sjakobi** [zenhack/haskell-capnp#85]
See https://hackage.haskell.org/package/capnp-0.15.0.0.

For previous versions the documentation is available on Hackage.

**Comment by zenhack** [comment]
Thanks for the report. I pushed a fix to master that fixes the doc build error. Looks like there's some other bitrot preventing it from building on the latest GHC, so I'll probably hold off on a release until I have the opportunity to fix that as well. But the docs for 0.14 should be nearly identical.

**Comment by zenhack** [comment]
Just published `0.16.0.0`. Docs are still 'pending', but I did remember to build them locally first this time, so I'm going to optimistically close this.

**Comment by sjakobi** [comment]
@zenhack The docs builder is apparently using GHC 8.10 – but `capnp` seems to require GHC 9.2 via the `template-haskell` bound.

See https://hackage.haskell.org/package/capnp-0.16.0.0/reports/2.

**Comment by zenhack** [comment]
Ack. Well, if you know how to get it to use a newer version for docs I'm all ears, but otherwise I don't think I'm inclined to fight with it.
