### ISSUE TITLE
Tutorial code examples wrong

### ISSUE THREAD

**Issue by cheater** [zenhack/haskell-capnp#89]
The code examples in the tutorial refer to modules that end in `.New`, but those modules, as they are now generated, do not end in `.New`.

**Comment by zenhack** [comment]
Thanks for the report. I must have forgotten to update this when I renamed them. Everything should work if you just drop all of the `.New`.

**Comment by zenhack** [comment]
Just pushed a fix to master, which will go out with the next release.

**Comment by cheater** [comment]
Thank you :)
